
=---
title: "glp1"
output: html_document
date: "2023-11-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE)
```

```{bash,eval=FALSE}
#in bash
grep -E 'Byetta|Ozempic|Wegovy|Bydureon|Trulicty|Lixumia|Victoza|Rybelsus|Liraglutide|Dulaglutide|Exenatide|Lixisenatide|Semaglutide' gp_scripts.txt >glpfile.txt
```


```{r}
source("~/multistate2/code/utils.R")
prs_subset=readRDS("~/Library/CloudStorage/Dropbox-Personal/pheno_dir/prs_subset.rds")
glp1=fread("~/Library/CloudStorage/Dropbox-Personal//glp1s.txt")
colnames(glp1)[1]=c("Identifier")
colnames(glp1)[3]=c("event_dt")
df_baseline=readRDS("~/Library/CloudStorage/Dropbox-Personal/pheno_dir/output/dfukb_baseline.rds")
glp1$event_dt <- as.Date(glp1$event_dt, format="%d/%m/%Y")
unique_patients <- glp1 %>%
  group_by(Identifier) %>%
  summarize(earliest_event_dt = min(event_dt))

m=merge(prs_subset,unique_patients,by = "Identifier",all.x = T)
m2=merge(m,df_baseline,by.x = "Identifier",by.y="identifier")

m2$treat=as.integer(ifelse(!is.na(m2$earliest_event_dt),1,0))
library(MatchIt)

biomarkers=readRDS("~/Library/CloudStorage/Dropbox-Personal/ukbb-ehr-data/data/biomarkers.rds")
bmi=biomarkers[biomarkers$variable%in%"bmi",]
bmi$date <- as.Date(bmi$date, format="%Y/%m/%d")
sorted_data <- bmi %>%
  arrange(eid, date) %>%
  group_by(eid)  %>%
  slice(n())


m2=m2[!is.na(m2$f.21001.0.0),]
mg=merge(m2,sorted_data,by.x="Identifier",by.y="eid")
mg$bmi.prs=mg$BMI
matched=matchit(treat~f.34.0.0+f.21001.0.0+f.31.0.0,data=mg)
summary(matched)
datm=match.data(matched)



datm$delta=(datm$value-datm$f.21001.0.0)/datm$f.21001.0.0

your_model=lm(scale(delta)~treat+treat:bmi.prs,dat=datm)


model_summary <- summary(your_model)

model_summary

coefficients <- model_summary$coefficients
rownames(coefficients)=c("(Intercept)","Treatment","Treatment:PRS")
# Create a data frame of PRS values (e.g., from min to max PRS in your data)
prs_values <- data.frame(PRS = seq(min(mg$BMI), max(mg$BMI), length.out = 100))

# Calculate predicted treatment effect for each PRS value
# Adjust the formula based on your model's structure
prs_values$Predicted_Effect <- coefficients["(Intercept)", "Estimate"] +
  coefficients["Treatment", "Estimate"] * 1 +
  coefficients["Treatment:PRS", "Estimate"] * 1 * prs_values$PRS

# Plot
library(ggplot2)
ggplot(prs_values, aes(x = PRS, y = Predicted_Effect)) +
  geom_line() +
  theme_minimal() +
  labs(title = "Predicted Treatment Effect Across PRS",
       x = "Polygenic Risk Score (PRS)",
       y = "Predicted Treatment Effect")

```





