---
title: "glp1"
output: html_document
date: "2023-11-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message = FALSE)

```


```{r dataread}
source("~/multistate2/code/utils.R")
library(MatchIt)
prs_subset=readRDS("~/Library/CloudStorage/Dropbox-Personal/pheno_dir/prs_subset.rds")
glp1=fread("~/Library/CloudStorage/Dropbox-Personal//glp1s_withi.txt")
colnames(glp1)[1]=c("Identifier")
colnames(glp1)[3]=c("event_dt")
df_baseline=readRDS("~/Library/CloudStorage/Dropbox-Personal/pheno_dir/output/dfukb_baseline.rds")
df_baseline=df_baseline[!is.na(df_baseline$f.21001.0.0),]
## treatment data 
glp1$event_dt <- as.Date(glp1$event_dt, format="%d/%m/%Y")
biomarkers=readRDS("~/Library/CloudStorage/Dropbox-Personal/ukbb-ehr-data/data/biomarkers.rds")
bmi=biomarkers[biomarkers$variable%in%"bmi",]
bmi$date <- as.Date(bmi$date, format="%Y/%m/%d")

```

Here you can see the medication used according to NHS. This results in 2200 prescriptions for 940 people.

```{bash,eval=FALSE,echo=TRUE}
#in bash
grep -E 'Byetta|Ozempic|Wegovy|Bydureon|Trulicity|Lixumia|Victoza|Rybelsus|Liraglutide|Dulaglutide|Exenatide|Lixisenatide|Semaglutide' gp_scripts.txt > glp1s_withi.txt
```


We match on sex, DOB, and BMI at baseline and display characteristics of population before and after matching.
```{r}
glp1_treated <- glp1 %>%
  group_by(Identifier) %>%
  summarize(first_script = min(event_dt))

```


Now BMI data:

```{r}
baseline_bmi=data.frame("eid"=df_baseline$identifier,"date"=as.Date(df_baseline$f.53.0.0),"variable"="bmi",source="ukb","value"=df_baseline$f.21001.0.0)
bmi2=rbind(bmi,baseline_bmi)

## merge with the date of treatment for treated folks
controls=bmi2[!(bmi2$eid%in%glp1_treated$Identifier),]
controls$bmi_date=as.Date(controls$date)


## treated
data2=merge(bmi2,glp1_treated,by.x="eid",by.y="Identifier")
data2$bmi_date=as.Date(data2$date)


last_bmi_before_script <- data2 %>%
  group_by(eid) %>%
  filter(bmi_date < first_script) %>%
  slice_max(order_by = bmi_date, n = 1) %>%
  distinct(eid, .keep_all = TRUE)


last_bmi_after_script <- data2 %>%
  group_by(eid) %>%
  filter(bmi_date > first_script) %>%
  slice_max(order_by = bmi_date, n = 1) %>%
  distinct(eid, .keep_all = TRUE)


bmis_treated=merge(last_bmi_before_script,last_bmi_after_script[,c("eid","bmi_date","value")],by="eid")
bmis_treated$delta=bmis_treated$value.y-bmis_treated$value.x
bmis_treated$duration=difftime(bmis_treated$bmi_date.y,bmis_treated$first_script,units = "days")

#only keep those with bmis measured at least 90 days out
bmis_treated=bmis_treated[bmis_treated$duration>90,]



## for controls last BMI before treatment will be baseline measure (f.210001.0)


controls_first <- controls %>%
  group_by(eid) %>%
  slice_min(order_by = bmi_date, n = 1) %>%
  distinct(eid, .keep_all = TRUE)

controls_last <- controls %>%
  group_by(eid) %>%
  slice_max(order_by = bmi_date, n = 1) %>%
  distinct(eid, .keep_all = TRUE)


controls_all=merge(controls_first,controls_last[,c("eid","bmi_date","value")],by="eid")
controls_all$difftimme=difftime(controls_all$bmi_date.y,controls_all$bmi_date.x,units="days")
controls_all=merge(controls_all,df_baseline,by.x = "eid",by.y="identifier")
## using first and last measurement
controls_all$delta=controls_all$value.y-controls_all$value.x
## this duration is too long
summary(as.numeric(controls_all$difftimme))

## distibrution looks similar if we use since base
controls_all$sincebase=as.numeric(difftime(controls_all$bmi_date.y,controls_all$f.53.0.0,units = "days"))
controls_all=controls_all[controls_all$sincebase>0,]

## compare the difference in date distribution
qqplot(as.numeric(controls_all$sincebase),as.numeric(controls_all$difftimme))
# only keep individuals with last measurement 
qqplot(as.numeric(controls_all$sincebase),as.numeric(bmis_treated$duration))

## Now merge
for_matching_treat=data.frame(
  "eid" = bmis_treated$eid,
  "firstval" = bmis_treated$value.x,
  "treatdate" = as.Date(bmis_treated$first_script),
  "lastval" = bmis_treated$value.y,
  "duration" = as.numeric(bmis_treated$duration),
  "delta" = bmis_treated$delta,
  "treat" = 1
)

for_matching_controls = data.frame(
  "eid" = controls_all$eid,
  "firstval" = controls_all$f.21001.0.0,
  "treatdate" = controls_all$f.53.0.0,
  "lastval" = controls_all$value.y,
  "duration" = controls_all$sincebase,
  "delta" = controls_all$value.y - controls_all$f.21001.0.0,
  "treat" = 0
)


for_matching=rbind(for_matching_treat,for_matching_controls)

for_matching=merge(for_matching,df_baseline,by.x = "eid",by.y="identifier")

for_matching = for_matching[, c(
  "eid",
  "firstval",
  "lastval",
  "treatdate",
  "delta",
  "duration",
  "f.21001.0.0",
  "f.31.0.0",
  "f.34.0.0",
  "f.53.0.0",
  "f.54.0.0",
  "treat"
)]
## only keep those whose last bmi measurement is after treatment and matchon this 

matched=matchit(treat~f.34.0.0+f.21001.0.0+f.31.0.0,data=for_matching)
summary(matched)
datm=match.data(matched)

datm=merge(datm,prs_subset[,c("Identifier","BMI","CAD")],by.x="eid",by.y="Identifier")
## grab the control delta as difference between the baseline BMI and the last measured BMI
datm$bmi.prs=datm$BMI
```

## Within treated populiaton

```{r}
your_model=lm(delta~bmi.prs+f.31.0.0,dat=datm[datm$treat==1,])
```



We now measure the percentage of BMI chance and calculate the influence of treatment, PRS, or the interaction:

```{r}

your_model=lm(scale(delta)~treat+treat:bmi.prs+f.31.0.0+f.21001.0.0,dat=datm)
your_model=lm(delta~treat+treat:bmi.prs,dat=datm,weights = weights)

model_summary <- summary(your_model)
model_summary
```

```{r}
boxplot(delta~treat,data = datm,ylab="Change in BMI")
hist(datm$duration[datm$treat==1]/365,xlab="Years on treatment",main="Density")
datm$prs.group=cut(datm$bmi.prs,breaks = quantile(datm$bmi.prs,probs = seq(0,1,by=0.1)),labels = c(1:10))
boxplot(delta~prs.group,data = datm,ylab="Change in BMI",xlab="BMI.PRS Decile")
```
