---
title: "Flashier"
output: html_document
date: "2023-11-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Let's do some flashing!

```{r cars}
library(flashier)
library(data.table)
filepath="~/Library/CloudStorage/Dropbox-Personal/pheno_dir/"

df.phecode.wide=readRDS("~/Library/CloudStorage/Dropbox-Personal/phecode/df.phecode.wide.rds")
#df.phecode.wide[is.na(df.phecode.wide)]=0

dfw=df.phecode.wide[,-c(1:5)]

## First create a sparse matrix of loadings on the non-9 ages

dfw[!is.na(dfw)]=1
dfw[is.na(dfw)]=0

X=as.matrix(dfw)
#install.packages("flashier")
## remove individuals never phenotyped

X=X[which(rowSums(X)>0),]

X=X[,which(colSums(X)>500)]
K=12
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE,eval=F}
fit_default <- flash(as.matrix(scale(X)), greedy_Kmax = 20)
plot(fit_default, pw_which = "factors")
saveRDS(fit_default,file=paste0(filepath,"fit_default_all.rds"))
```

```{r}
fit=readRDS(paste0(filepath,"fit_default_all.rds"))

dim(fit$F_pm)[1]
plot(fit, pw_which = "factors")
```


# Less than 40
```{r lessthan40,eval=F}
K=12
dfw=df.phecode.wide[,-c(1:5)]

## First create a sparse matrix of loadings on the non-NA ages
# Assuming your data.table is named your_data_table
age_threshold <- 40  # Replace with your desired age threshold

# Apply the operation to all columns
dfw[, (1:ncol(dfw)) := lapply(.SD, function(x) ifelse(!is.na(x) & x < age_threshold, 1, 0))]


X=as.matrix(dfw)
#install.packages("flashier")
## remove individuals never phenotyped
X=X[which(rowSums(X)>0),]
X=X[,which(colSums(X)>500)]

print(dim(X))

fit_default40 <- flash(as.matrix(scale(X)), greedy_Kmax = K)
plot(fit_default40, pw_which = "factors")
saveRDS(fit_default40,file=paste0(filepath,"fit_default40.rds"))
```

```{r}
filepath="~/Library/CloudStorage/Dropbox-Personal/pheno_dir/"

fit=readRDS(paste0(filepath,"fit_default40.rds"))
dim(fit$F_pm)[1]
plot(fit, pw_which = "factors")
```

## now let's only look at disease that occur before 50

```{r lessthan50,eval=F}
K=12
dfw=df.phecode.wide[,-c(1:5)]

## First create a sparse matrix of loadings on the non-NA ages
# Assuming your data.table is named your_data_table
age_threshold <- 50  # Replace with your desired age threshold

# Apply the operation to all columns
dfw[, (1:ncol(dfw)) := lapply(.SD, function(x) ifelse(!is.na(x) & x < age_threshold & x >(age_threshold-10), 1, 0))]


X=as.matrix(dfw)
#install.packages("flashier")
## remove individuals never phenotyped
X=X[which(rowSums(X)>0),]
X=X[,which(colSums(X)>500)]


print(dim(X))

fit_default50 <- flash(as.matrix(scale(X)), greedy_Kmax = K)
plot(fit_default50, pw_which = "factors")
saveRDS(fit_default50,file=paste0(filepath,"fit_default50.rds"))
```

```{r}
fit=readRDS(paste0(filepath,"fit_default50.rds"))
dim(fit$F_pm)[1]
plot(fit, pw_which = "factors")
```

## 50-60

```{r between50.60,eval=F}

dfw=df.phecode.wide[,-c(1:5)]

## First create a sparse matrix of loadings on the non-NA ages

## First create a sparse matrix of loadings on the non-NA ages
# Assuming your data.table is named your_data_table
age_threshold <- 60  # Replace with your desired age threshold

# Apply the operation to all columns
dfw[, (1:ncol(dfw)) := lapply(.SD, function(x) ifelse(!is.na(x) & x < age_threshold & x > (age_threshold-10), 1, 0))]




X=as.matrix(dfw)
#install.packages("flashier")
## remove individuals never phenotyped

X=X[which(rowSums(X)>0),]
X=X[,which(colSums(X)>500)]
print(dim(X))

fit_default60 <- flash(as.matrix(scale(X)), greedy_Kmax = K)
plot(fit_default60, pw_which = "factors")
saveRDS(fit_default60,file=paste0(filepath,"fit_default60.rds"))
```

```{r}
fit=readRDS(paste0(filepath,"fit_default60.rds"))
dim(fit$F_pm)[1]
plot(fit, pw_which = "factors")
```


```{r betw6070,eval=F}
dfw=df.phecode.wide[,-c(1:5)]
## First create a sparse matrix of loadings on the non-NA ages
## First create a sparse matrix of loadings on the non-NA ages
# Assuming your data.table is named your_data_table
age_threshold <- 70  # Replace with your desired age threshold

# Apply the operation to all columns
dfw[, (1:ncol(dfw)) := lapply(.SD, function(x) ifelse(!is.na(x) & x < age_threshold & x > (age_threshold-10), 1, 0))]

X=as.matrix(dfw)
#install.packages("flashier")
## remove individuals never phenotyped
X=X[which(rowSums(X)>0),]
X=X[,which(colSums(X)>500)]

print(dim(X))

fit_default70 <- flash(as.matrix(scale(X)), greedy_Kmax = K)
plot(fit_default70, pw_which = "factors")
saveRDS(fit_default70,file=paste0(filepath,"fit_default70.rds"))
```


```{r}
fit=readRDS(paste0(filepath,"fit_default70.rds"))
dim(fit$F_pm)[1]
plot(fit, pw_which = "factors")
```

```{r greater70,eval=F}
dfw=df.phecode.wide[,-c(1:5)]
## First create a sparse matrix of loadings on the non-NA ages

## First create a sparse matrix of loadings on the non-NA ages
# Assuming your data.table is named your_data_table
age_threshold <- 70  # Replace with your desired age threshold

# Apply the operation to all columns
dfw[, (1:ncol(dfw)) := lapply(.SD, function(x) ifelse(!is.na(x) & x > (age_threshold), 1, 0))]

X=as.matrix(dfw)
#install.packages("flashier")
## remove individuals never phenotyped
X=X[which(rowSums(X)>0),]
X=X[,which(colSums(X)>500)]

print(dim(X))
fit_defaultold <- flash(as.matrix(scale(X)), greedy_Kmax = K)
saveRDS(fit_defaultold,file=paste0(filepath,"fit_defaultold.rds"))
```


```{r}
fit=readRDS(paste0(filepath,"fit_defaultold.rds"))
dim(fit$F_pm)[1]
plot(fit, pw_which = "factors")
```

## Let's examine to see if the factors are similar among ages

```{r}
overall=readRDS(paste0(filepath,"fit_default_all.rds"))
head(sort(overall$F_pm[,1],decreasing = T),100)
head(sort(overall$F_pm[,2],decreasing = T),100)


fit40=readRDS(paste0(filepath,"fit_default40.rds"))
head(sort(fit40$F_pm[,1],decreasing = T),10)
head(sort(fit40$F_pm[,2],decreasing = T),10)

fit50=readRDS(paste0(filepath,"fit_default50.rds"))
head(sort(fit50$F_pm[,1],decreasing = T),10)
head(sort(fit50$F_pm[,2],decreasing = T),10)

fit60=readRDS(paste0(filepath,"fit_default60.rds"))
head(sort(fit60$F_pm[,1],decreasing = T),10)
head(sort(fit60$F_pm[,2],decreasing = T),10)

fit70=readRDS(paste0(filepath,"fit_default70.rds"))
head(sort(fit70$F_pm[,1],decreasing = T),10)
head(sort(fit70$F_pm[,2],decreasing = T),10)

fitold=readRDS(paste0(filepath,"fit_defaultold.rds"))
head(sort(fitold$F_pm[,1],decreasing = T),10)
head(sort(fitold$F_pm[,2],decreasing = T),10)
```

```{r}
df.phecode.wide=readRDS("~/Library/CloudStorage/Dropbox-Personal/df.phecode.wide_rollup.rds")
X=df.phecode.wide[,-c(1:5)]
X[is.na(X)]=0

X=as.matrix(X)

X=X[which(rowSums(X!=0)>0),]

X=X[,which(colSums(X!=0)>500)]

new_array <- array(0, dim = c(9, nrow(X), ncol(X)))

# Function to determine the age category
get_age_category <- function(age) {
  if (age == 0) return(NA)  # No age information
  else if (age < 30) return(1)
  else if (age >= 30 && age < 40) return(2)
  else if (age >= 40 && age < 45) return(3)
  else if (age >= 45 && age < 50) return(4)
  else if (age >= 55 && age < 60) return(5)
  else if (age >= 65 && age < 70) return(6)
  else if (age >= 70 && age < 75) return(7)
  else if (age >= 75 && age < 80) return(8)
  else return(9)  # 80 and over
}


current_matrix=X
# Pxopulate the new array
# Populate the new array
for (person in 1:nrow(current_matrix)) {
  for (code in 1:ncol(current_matrix)) {
    age <- current_matrix[person, code]
    age_category <- get_age_category(age)
    if (!is.na(age_category)) {
      new_array[age_category, person, code] <- 1
      
    }
  }
}

f=flashier::flash(new_array,greedy_Kmax = 10,ebnm_fn = c(ebnm_point_normal,ebnm_point_exponential,ebnm_point_laplace))
saveRDS(f,"flasharrayrolup_9andsparse.rds")

f=flashier::flash(new_array,greedy_Kmax = 10,ebnm_fn = c(ebnm_point_normal,ebnm_point_exponential,ebnm_point_laplace))
saveRDS(f,"flasharrayrolup.rds")

f2=flashier::flash(new_array,greedy_Kmax = 10,ebnm_fn = c(ebnm_point_normal,ebnm_point_exponential,ebnm_point_laplace))

### don't interpret the first factor (essentially the intercept term)
### for ebnm, pass the smoothing function ebnm_fn(c(eb

```

```{r}
