---
title: "Time Dependency"
output:
  ioslides_presentation:
    widescreen: true
    smaller: true
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE,cache = FALSE,warning = FALSE,message = FALSE)
```


```{r,eval=FALSE}
file_paths <- list.files(path = "~/Desktop/output_gp/", pattern = "\\.tab\\.tsv\\.gz$", full.names = TRUE)
merged_has <- data.table(sample_id = integer(0))

for (file_path in file_paths) {
  file_name <- gsub(".tab.tsv.gz$", "", basename(file_path))
  file_data <-fread(file_path,select = c("sample_id", "has_disease"))
  fd = file_data[, c("sample_id", "has_disease")]
  names(fd)[2] = paste0(file_name, ":has_disease")

  # Merge data based on patient_id
  if (ncol(merged_has) == 1) {
    merged_has <- fd
  } else {
    merged_has <-
      merge(merged_has,
            fd,
            by =  "sample_id",
            all = TRUE)
  }
}

merged_has[is.na(merged_has)]=0


colnames(merged_has)[-1]=stringr::str_split_fixed(names(merged_has)[-1],pattern = ":",n = 2)[,1]
saveRDS(merged_has,file = "~/Library/CloudStorage/Dropbox-Personal/merged_has.rds")

merged_censor <- data.table(sample_id = integer(0))

for (file_path in file_paths) {
  file_name <- gsub(".tab.tsv.gz$", "", basename(file_path))
  file_data <-fread(file_path,select = c("sample_id","censor_age"))
  fd = file_data[, c("sample_id", "censor_age")]

  names(fd)[2] = paste0(file_name, ":censor_age")
  # Merge data based on patient_id
  if (ncol(merged_censor) == 1) {
    merged_censor <- fd
  } else {
    merged_censor <-
      merge(merged_censor,
            fd,
            by =  "sample_id",
            all = TRUE)
  }
}

saveRDS(merged_censor,file="~/Desktop/output_gp/merged_censor.rds")
```



```{r,eval=T}
library(data.table)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)

merged_has=readRDS("~/Desktop/output_gp/merged_has.rds")
merged_censor=readRDS("~/Desktop/output_gp/merged_censor.rds")
bad = c(
  grep(x = colnames(merged_has), pattern = "composite"),
  grep(x = colnames(merged_has), pattern = "HARD"),
  grep(x = colnames(merged_has), pattern = "SOFT"),
  grep(x = colnames(merged_has), pattern = "INTERMEDIATE"),
  grep(x = colnames(merged_has), pattern = "imaging"),
  grep(x = colnames(merged_has), pattern = "v2"),
  grep(x = colnames(merged_has), pattern = "UKBB"),
  grep(x = colnames(merged_has), pattern = "ukbb"),
  grep(x = colnames(merged_has), pattern = "self"), 
  grep(x = colnames(merged_has), pattern = "inclusive"), 
  grep(x = colnames(merged_has), pattern = "only"))

bad=unique(bad)
merged_censor <- merged_censor[, (bad) := NULL]
merged_has <- merged_has[, (bad) := NULL]

colnames(merged_censor)[-1]=colnames(merged_has)[-1]=stringr::str_split_fixed(names(merged_censor)[-1],pattern = ":",n = 2)[,1]

disease_df <- as.data.frame(merged_has)
age_df <- as.data.frame(merged_censor)


a=apply(disease_df,2,function(x){sum(is.na(x))})

# Calculate the co-occurrence matrix
disease_matrix=disease_df[,a==0]
time_matrix=age_df[,a==0]

disease_mx=as.matrix(disease_matrix[,-1])
censor_mx= (disease_mx + 1) %% 2
age_mx=time_matrix[,-1]

co_occurrence_matrix <- t(disease_mx)%*%(disease_mx)

###
# Convert the age matrix into a bin matrix
age_bins <- matrix(NA, nrow = nrow(age_mx), ncol = ncol(age_mx))
for (i in 1:ncol(age_mx)) {
  age_bins[, i] <- cut(age_mx[, i], breaks = c(0,20,40,50,60,70,80,90,100), labels = FALSE)
}

l=levels(cut(age_mx[,1], breaks = c(0,20,40,50,60,70,80,90)))

co_occurrence_by_age <- list()

# Get unique age bins; assuming age_bins is a matrix with the same dimensions as disease_mx
unique_age_bins <- unique(as.vector(age_bins))
v=levels(cut(seq(1:100), breaks = c(0,20,40,50,60,70,80,90)))

#for(i in 1:length(l)){
 
# Loop through each unique age bin
for(bin in 1:length(unique_age_bins)) {
  # Create a mask for rows corresponding to the current age bin and uncensored data
  mask <- (age_bins == bin)
 print(v[bin])
  # Subset the disease matrix based on the mask
  # Create a matrix of the same dimensions filled with NA
  disease_subset <- matrix(0, nrow=nrow(disease_mx), ncol=ncol(disease_mx))

  # Fill in the values where mask is TRUE
  disease_subset[mask] <- disease_mx[mask]

  # Compute the co-occurrence matrix using fast matrix multiplication
  co_occurrence_matrix <- t(disease_subset) %*% disease_subset
  colnames(co_occurrence_matrix)=rownames(co_occurrence_matrix)=colnames(disease_mx)
  lt=lower.tri(co_occurrence_matrix)
  co_occurrence_matrix[lt]=NA
  
  co_occurrence_long <- as.data.frame(as.table(co_occurrence_matrix))
  co_occurrence_long <- co_occurrence_long %>%
    filter(Var1 != Var2)
  sorted_co_occurrence <- co_occurrence_long %>%
    arrange(desc(Freq))
  top_pairs <- head(sorted_co_occurrence, n=10)
  print(top_pairs)
 
  # phenotype_summary <- sorted_co_occurrence %>%
  #   group_by(Var1) %>%
  #   summarise(num_correlated_phenotypes = n(),
  #             correlated_phenotypes = toString(Var2))


}



# saveRDS(co_occurrence_by_age,file = "~/Library/CloudStorage/Dropbox-Personal//cooccurencebyage.rds")
#   
```

```{r}

l=readRDS("~/Library/CloudStorage/Dropbox-Personal//cooccurencebyage.rds")

v=levels(cut(seq(1:100), breaks = c(0,20,40,50,60,70,80,90,100)))
i=1
#for(i in 1:length(l)){
  print(v[i])
  co_occurrence_matrix=l[[i]]
  co_matrix_melted <- as.data.frame(as.table(co_occurrence_matrix))
  gg <- ggplot(data = co_matrix_melted, aes(x=Var1, y=Var2)) +
    geom_tile(aes(fill = Freq), color = "white") +
    scale_fill_gradient(low = "white", high = "red") +
    theme_minimal() +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank()
    )


  ggplotly(gg)
  # Add co-occurrence matrix to list
  
#}

```

```{r}

i=2
#for(i in 1:length(l)){
  print(v[i])
  co_occurrence_matrix=l[[i]]
  co_matrix_melted <- as.data.frame(as.table(co_occurrence_matrix))
  gg <- ggplot(data = co_matrix_melted, aes(x=Var1, y=Var2)) +
    geom_tile(aes(fill = Freq), color = "white") +
    scale_fill_gradient(low = "white", high = "red") +
    theme_minimal() +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank()
    )


  ggplotly(gg)
  # Add co-occurrence matrix to list
  
#}

```


```{r}

i=3
#for(i in 1:length(l)){
  print(v[i])
  co_occurrence_matrix=l[[i]]
  co_matrix_melted <- as.data.frame(as.table(co_occurrence_matrix))
  gg <- ggplot(data = co_matrix_melted, aes(x=Var1, y=Var2)) +
    geom_tile(aes(fill = Freq), color = "white") +
    scale_fill_gradient(low = "white", high = "red") +
    theme_minimal() +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank()
    )


  ggplotly(gg)
  # Add co-occurrence matrix to list
  
#}

```


```{r}

i=4
#for(i in 1:length(l)){
  print(v[i])
  co_occurrence_matrix=l[[i]]
  co_matrix_melted <- as.data.frame(as.table(co_occurrence_matrix))
  gg <- ggplot(data = co_matrix_melted, aes(x=Var1, y=Var2)) +
    geom_tile(aes(fill = Freq), color = "white") +
    scale_fill_gradient(low = "white", high = "red") +
    theme_minimal() +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank()
    )


  ggplotly(gg)
  # Add co-occurrence matrix to list
  
#}

```


```{r}

i=5
#for(i in 1:length(l)){
  print(v[i])
  co_occurrence_matrix=l[[i]]
  co_matrix_melted <- as.data.frame(as.table(co_occurrence_matrix))
  gg <- ggplot(data = co_matrix_melted, aes(x=Var1, y=Var2)) +
    geom_tile(aes(fill = Freq), color = "white") +
    scale_fill_gradient(low = "white", high = "red") +
    theme_minimal() +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank()
    )


  ggplotly(gg)
  # Add co-occurrence matrix to list
  
#}

```


```{r}

i=6
#for(i in 1:length(l)){
  print(v[i])
  co_occurrence_matrix=l[[i]]
  co_matrix_melted <- as.data.frame(as.table(co_occurrence_matrix))
  gg <- ggplot(data = co_matrix_melted, aes(x=Var1, y=Var2)) +
    geom_tile(aes(fill = Freq), color = "white") +
    scale_fill_gradient(low = "white", high = "red") +
    theme_minimal() +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank()
    )


  ggplotly(gg)
  # Add co-occurrence matrix to list
  
#}

```

```{r}

i=7
#for(i in 1:length(l)){
  print(v[i])
  co_occurrence_matrix=l[[i]]
  co_matrix_melted <- as.data.frame(as.table(co_occurrence_matrix))
  gg <- ggplot(data = co_matrix_melted, aes(x=Var1, y=Var2)) +
    geom_tile(aes(fill = Freq), color = "white") +
    scale_fill_gradient(low = "white", high = "red") +
    theme_minimal() +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank()
    )


  ggplotly(gg)
  # Add co-occurrence matrix to list
  
#}

```


```{r}

i=8
#for(i in 1:length(l)){
  print(v[i])
  co_occurrence_matrix=l[[i]]
  co_matrix_melted <- as.data.frame(as.table(co_occurrence_matrix))
  gg <- ggplot(data = co_matrix_melted, aes(x=Var1, y=Var2)) +
    geom_tile(aes(fill = Freq), color = "white") +
    scale_fill_gradient(low = "white", high = "red") +
    theme_minimal() +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank()
    )


  ggplotly(gg)
  # Add co-occurrence matrix to list
  
#}

```


