---
title: "tenyear"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library("ggsci")
library(dplyr)
library(tidyr)
library(data.table)
library(ggplot2)
library(ggpubr)

test=readRDS("~/multistate2/output/test.rds")
pce.reverse.tenyear=readRDS("~/multistate2/output/pce.reverse.tenyear.rds")
ascvd.30.year=readRDS("~/multistate2/output/ascvd.30year.rds")
#ascvd.30.year.rc=readRDS("~/multistate2/output/ascvd.30year.rc.rds")
ascvd.30.year.rc=readRDS("~/multistate2/output/ascvd.30year.rcnew.rds")


# ages=c(40:79)
# a=data.frame(cbind(ascvd.30.year,lev=test$int))
# a$metric=rep("30y",nrow(a))
# 
# b=data.frame(cbind(ascvd.30.year.rc,lev=test$int))
# b$metric=rep("30yRC",nrow(b))
# ab=rbind(a,b)
# colnames(ab)=c(ages,"score","metric")
# 
# t=melt(ab,id.vars = c("score","metric"))
# 
# # Calculate mean values for each combination
# df_mean <- t %>%
#   group_by(score, metric, variable) %>%
#   summarise(mean_value = mean(value, na.rm = TRUE))
# 
# df_mean <- df_mean %>%
#   mutate(
#     gender = case_when(
#       score %% 2 == 0 ~ "Male",
#       TRUE ~ "Female"
#     ),
#     percentile = case_when(
#       score %in% c(1,2) ~ "0.2",
#       score %in% c(3,4) ~ "0.5",
#       score %in% c(5,6) ~ "0.8",
#       TRUE ~ as.character(score)
#     )
#   )
# 
# 
# gf=ggplot(df_mean, aes(x = as.numeric(variable), y = mean_value, col = as.factor(interaction(gender,score)),shape=metric)) +
#   geom_point() +
#   labs(x = "Age", y = "Predicted Lifetime Risk",col="Sex, PRS Percent",shape="FRS") +
#   theme_classic()

# ggsave(gf,file="../output/gf.pdf",dpi=600)
#          

head(pce.reverse.tenyear)
agesint=c(40:80)
thresh=5;
ten=apply(pce.reverse.tenyear,1,function(x){min(agesint[x>thresh])})
thresh=10;


### this is the data frame with approportiate score
states=readRDS("~/multistate2/output/state_occupancy_risk.rds")
ages=c(40:80)
thresh=0.10;
t=sapply(1:length(states),function(x){w=which(states[[x]]>thresh);ifelse(length(w)>0,min(ages[w]),100)})

df=data.frame("id"=test$identifier,"Cad_0_Any"=test$Cad_0_Any,"Cad_0_censor_age"=test$Cad_0_censor_age,"sex"=test$f.31.0.0,"prs"=test$cad.prs,"ten"=ten,"ms"=t)
df_expanded <- data.frame(
  id = integer(), 
  start = numeric(), 
  stop = numeric(), 
  event = integer(), 
  score1 = integer(), 
  score2 = integer()
)


library(data.table)

# Convert df to data.table
# Convert df to data.table
setDT(df)

expand_data <- function(id, cad_status, censor_age, score1_age, score2_age) {
  ages <- sort(c(40, score1_age, score2_age, censor_age))
  result <- list()
  
  for(j in 1:(length(ages) - 1)) {
    start_age <- ages[j]
    stop_age <- ages[j+1]
    
    if(start_age == stop_age) next # skip if they are the same
    
    s1 <- ifelse(start_age >= score1_age, 1, 0)
    s2 <- ifelse(start_age >= score2_age, 1, 0)
    
    event_at_stop <- ifelse(stop_age == censor_age && cad_status == 2, 1, 0)
    
    result[[length(result) + 1]] <- list(id = id, start = start_age, stop = stop_age, event = event_at_stop, score1 = s1, score2 = s2)
  }
  
  return(result)
}

list_dt <- lapply(1:nrow(df), function(i) {
  row <- df[i,]
  expand_data(row$id, row$Cad_0_Any, row$Cad_0_censor_age, row$ten, row$ms)
})

df_expanded <- rbindlist(unlist(list_dt, recursive = FALSE))




library(survival)

# Bootstrap function for C-index
bootstrap_cindex <- function(fit_function, data, n_iter=10) {
  cindices <- numeric(n_iter)
  
  for(i in 1:n_iter) {
    sample_rows <- sample(1:nrow(data), replace = TRUE)
    sample_data <- data[sample_rows, ]
    
    fit <- fit_function(sample_data)
    cindices[i] <- summary(fit)$concordance[1]
  }
  
  return(list(mean = mean(cindices), se = sd(cindices)))
}

# Fit functions for score1 and score2
fit_function_score1 <- function(data) coxph(Surv(start, stop, event) ~ score1, data = data)
fit_function_score2 <- function(data) coxph(Surv(start, stop, event) ~ score2, data = data)


# Bootstrap C-index

results_score1 <- bootstrap_cindex(fit_function_score1, df_expanded)
results_score2 <- bootstrap_cindex(fit_function_score2, df_expanded)


# Confidence intervals (95%)
ci_score1 <- c(results_score1$mean - 1.96*results_score1$se, results_score1$mean + 1.96*results_score1$se)
ci_score2 <- c(results_score2$mean - 1.96*results_score2$se, results_score2$mean + 1.96*results_score2$se)

# Plot using ggplot2
library(ggplot2)

df_cindex <- data.frame(
  Score = c("MSGene","PCE 10 Year"),
  Cindex = c(results_score2$mean,results_score1$mean),
  ymin = c(ci_score2[1],ci_score1[1]),
  ymax = c(ci_score2[2],ci_score1[1])
)

cp <- ggplot(df_cindex, aes(x = Score, y = Cindex,fill=Score)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin=ymin, ymax=ymax), width=0.1, position=position_dodge(0.9)) +
  ylim(0,0.8 ) +
  labs(
    title = "Comparison of Predictive Performance",
    subtitle = "Using Bootstrap 95% CI for C-index (Concordance Index)",
    y = "C-index Value",
    x = ""
  ) +
  theme_classic()+scale_fill_aaas()

print(cp)
fit1 <- coxph(Surv(start, stop, event) ~ score1, data = df_expanded)
fit2 <- coxph(Surv(start, stop, event) ~ score2, data = df_expanded)

# Comparing models based on AIC
aic1 <- AIC(fit1)
aic2 <- AIC(fit2)

cat("AIC for FRS.30y:", aic1, "\n")
cat("AIC for msGene:", aic2, "\n")

# ggsave(ggarrange(p,p2,p3,cp,nrow=2,ncol=2),file="../output/thresholdexceeded.pdf")
```



Now do for continous variable brier score:


```{r}
df=test
score1_list=states
score2=pce.reverse.tenyear
df$Cad_0_censor_age=round(df$Cad_0_censor_age,0)
df$Cad_0_Any=ifelse(df$Cad_0_Any==2,1,0)




expanded_df <- data.frame()
df=test
score1_list=states
names(states)=df$identifier
score2=ascvd.30.year.rc
rownames(score2)=df$identifier
df$Cad_0_censor_age=round(df$Cad_0_censor_age,0)
df$Cad_0_Any=ifelse(df$Cad_0_Any==2,1,0)

bad_indices=which(df$Cad_0_censor_age>=80&df$Cad_0_Any==1)

# Removing the bad IDs from score1_list
score1_list <- score1_list[-bad_indices]

# Removing the bad IDs from score2 dataframe
score2 <- score2[-bad_indices, ]


df=df[-which(df$Cad_0_censor_age>=80&df$Cad_0_Any==1),]
dim(df)

all.equal(as.numeric(names(score1_list)),as.numeric(df$identifier))

all.equal(as.numeric(rownames(score2)),as.numeric(df$identifier))
# Initialize a list to store the results
expanded_list <- vector("list", length = nrow(df))

for(i in 1:nrow(df)) {
  #print(i)
  id <- df$id[i]
  max_age <- df$Cad_0_censor_age[i]
  event <- df$Cad_0_Any[i]
  
  # When max_age is less than 40 or length of score1_list[i] is 0
  if (max_age < 40 || length(score1_list[[i]]) == 0) {
    next  # Skip this iteration and proceed to the next
  }
  
  age_range <- 40:(40 + length(score1_list[[i]]) - 1)
  score1_values <- score1_list[[i]]
  score2_values <- score2[i, age_range - 39]
  
  # If there's an event and score1 is shorter than expected
  if (event == 1 && max(age_range) < max_age) {
    extended_age_range <- (max(age_range) + 1):max_age  
    score1_last_value <- rep(tail(score1_list[[i]], 1), times = length(extended_age_range))
    score1_values <- c(score1_list[[i]], score1_last_value)
    score2_last_value <- score2[i,(extended_age_range-39)]
    score2_values <- c(score2_values, score2_last_value)
    age_range <- c(age_range, extended_age_range)
  }
  
  # Store the resulting dataframe as a list element
  expanded_list[[i]] <- data.frame(id = id,
                                   age = age_range,
                                   score1 = score1_values,
                                   score2 = score2_values,
                                   event = ifelse(age_range == max_age, event, 0))
}

# Combine all the dataframes in the list at once
expanded_df <- do.call(rbind, expanded_list)
expanded_df$score1=expanded_df$score1*100
expanded_df$start <- expanded_df$age
expanded_df$stop <- expanded_df$age + 1


print(dim(expanded_df))

# Bootstrap C-index
results_score1 <- bootstrap_cindex(fit_function_score1, expanded_df)
results_score2 <- bootstrap_cindex(fit_function_score2, expanded_df)

# Confidence intervals (95%)
ci_score1 <- c(results_score1$mean - 1.96*results_score1$se, results_score1$mean + 1.96*results_score1$se)
ci_score2 <- c(results_score2$mean - 1.96*results_score2$se, results_score2$mean + 1.96*results_score2$se)

# Plot using ggplot2
library(ggplot2)

df_cindex <- data.frame(
  Score = c( "MSGene","PCE 10 Year"),
  Cindex = c(results_score1$mean, results_score2$mean),
  ymin = c(ci_score1[1], ci_score2[1]),
  ymax = c(ci_score1[2], ci_score2[2])
)

p <- ggplot(df_cindex, aes(x = Score, y = Cindex,fill=Score)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin=ymin, ymax=ymax), width=0.1, position=position_dodge(0.9)) +
  ylim(0,0.8 ) +
  labs(
    title = "Comparison of Predictive Performance",
    subtitle = "Using Bootstrap 95% CI for C-index (Concordance Index)",
    y = "C-index Value",
    x = ""
  ) +
  theme_classic()+scale_fill_aaas()

print(p)

saveRDS(p,"../output/continuosums_ten.rds")

####

```



```{r}
library(survival)
#ri=sample(unique(expanded_df$id),1000)
#sub=expanded_df[expanded_df$id%in%ri,]
cox_model <- coxph(Surv(start, stop, event) ~ score1, data = expanded_df,x = T)
library(pec)
### create a vector of predicted survival for every individual based on their profile at that time
time_points <- c(41:80)
brier.score=matrix(NA,nrow=2,ncol=length(time_points))
surv_probs <- predictSurvProb(object = cox_model,newdata=expanded_df, times=time_points)
colnames(surv_probs)=time_points
df=cbind(expanded_df,surv_probs)
dgood=df[df$age%in%time_points,]

for(j in 1:length(time_points)){
    dat=dgood[dgood$age==time_points[j],]
    surv=ifelse(dat$event==0,1,0)
    psurv=dat[,(j+7)]
    print(mean((surv-psurv)^2))
    brier.score[1,j]=mean((surv-psurv)^2)
    
    
}

rm(cox_model)
rm(surv_probs)
rm(df)
rm(dat)
cox_model <- coxph(Surv(start, stop, event) ~ score2, data = expanded_df,x = T)
time_points <- c(41:80)
### create a vector of predicted survival for every individual based on their profile at that time over a variety of time points

surv_probs <- predictSurvProb(object = cox_model,newdata=expanded_df, times=time_points)


colnames(surv_probs)=time_points
df=cbind(expanded_df,surv_probs)
dgood=df[df$age%in%time_points,]

for(j in 1:length(time_points)){
    dat=dgood[dgood$age==time_points[j],]
    surv=ifelse(dat$event==0,1,0)
    psurv=dat[,(j+7)]
    print(mean((surv-psurv)^2))
    brier.score[2,j]=mean((surv-psurv)^2)
    
}

bs=data.frame(t(brier.score))
bs$Age=time_points
colnames(bs)=c("MSGene","FRS30y","Time")
bs=melt(bs,id.vars = "Time")
ggplot(bs,aes(x=Time,y=value,fill=variable))+geom_bar(stat = "identity",position = "dodge")+labs(x="Time Point",y="Brier Score",fill="Score")+theme_classic()


###

cox_model <- coxph(Surv(start, stop, event) ~ score2, data = expanded_df,x = T)
time_points <- c(41:80)
### create a vector of predicted survival for every individual based on their profile at that time over a variety of time points
surv_probs <- predictSurvProb(object = cox_model,newdata=expanded_df, times=time_points)
colnames(surv_probs)=time_points
df=cbind(expanded_df,surv_probs)
dgood=df[df$age%in%time_points,]

dfevent=test[,c("identifier","Cad_0_Any","Cad_0_censor_age")]
m=merge(dgood[,c("id","age","80")],dfevent,by.x="id",by.y="identifier",all.x =T)
m$surv=ifelse(m$Cad_0_Any==1,1,0)

for(j in 1:length(time_points)){
    dat=m[m$age==time_points[j],]
    surv=dat$surv
    psurv=dat[,"80"]
    print(mean((surv-psurv)^2))
    brier.score[2,j]=mean((surv-psurv)^2)
    
}



###


cox_model <- coxph(Surv(start, stop, event) ~ score1, data = expanded_df,x = T)
time_points <- c(41:80)
### create a vector of predicted survival for every individual based on their profile at that time over a variety of time points
surv_probs <- predictSurvProb(object = cox_model,newdata=expanded_df, times=time_points)
colnames(surv_probs)=time_points
df=cbind(expanded_df,surv_probs)
dgood=df[df$age%in%time_points,]

dfevent=test[,c("identifier","Cad_0_Any","Cad_0_censor_age")]
m=merge(dgood[,c("id","age","80")],dfevent,by.x="id",by.y="identifier",all.x =T)
m$surv=ifelse(m$Cad_0_Any==1,1,0)

for(j in 1:length(time_points)){
    dat=m[m$age==time_points[j],]
    surv=dat$surv
    psurv=dat[,"80"]
    print(mean((surv-psurv)^2))
    brier.score[1,j]=mean((surv-psurv)^2)
    
}


bs=data.frame(t(brier.score))
bs$Age=time_points
colnames(bs)=c("MSGene","FRS30y","Time")
bs=melt(bs,id.vars = "Time")
ggplot(bs,aes(x=Time,y=value,fill=variable))+geom_bar(stat = "identity",position = "dodge")+labs(x="Time Point",y="Brier Score",fill="Score")+theme_classic()

```

